# Generated by Django 4.1.7 on 2023-04-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_cover_pic'),
        ('myapp', '0004_userprofile_coverpic'),
    ]

    operations = [
    ]
